# -*- coding: utf-8 -*-
"""Генерує DATA-блок меню El Clásico з упорядкованого джерела.
Кожна страва: ціна, алергени, назва+опис 6 мовами.
Дублікати між крейдяним і друкованим меню усунені."""
import json

# Порядок мов у кожному словнику
# es, en, de, fr, nl, uk

def M(es, en, de, fr, nl, uk):
    return {"es": es, "en": en, "de": de, "fr": fr, "nl": nl, "uk": uk}

sections = []

def sec(sid, name, note, items):
    sections.append({"id": sid, "name": name, "note": note, "items": items})

def it(p, alg, n, d, pop=False):
    o = {"p": p, "alg": alg, "n": n, "d": d}
    if pop:
        o["pop"] = True
    return o

EMPTY = M("", "", "", "", "", "")

# ============ TAPAS ============
sec("tapas",
    M("Tapas", "Tapas", "Tapas", "Tapas", "Tapas", "Тапас"),
    EMPTY,
    [
        it("2,00", [], 
           M("Aceitunas o patatas chips","Olives or crisps","Oliven oder Chips","Olives ou chips","Olijven of chips","Оливки або чипси"),
           M("Para picar mientras llega el resto.","To nibble while the rest arrives.","Zum Knabbern, bis der Rest kommt.","À grignoter en attendant.","Om te knabbelen terwijl de rest komt.","Поки готується решта.")),
        it("3,50", ["gluten"],
           M("Pan con alioli y tomate","Bread with aioli & tomato","Brot mit Aioli und Tomate","Pain à l'aïoli et tomate","Brood met aioli en tomaat","Хліб з айолі та томатом"),
           M("Pan tostado, alioli casero y tomate.","Toasted bread, house aioli and tomato.","Geröstetes Brot, hausgemachtes Aioli und Tomate.","Pain grillé, aïoli maison et tomate.","Geroosterd brood, huisgemaakte aioli en tomaat.","Тости, домашнє айолі й томат.")),
        it("4,50", ["huevo","pescado"],
           M("Ensaladilla rusa","Russian salad","Russischer Salat","Salade russe","Russische salade","Олів'є"),
           M("La clásica, con atún y mayonesa.","The classic, with tuna and mayo.","Der Klassiker, mit Thunfisch und Mayo.","La classique, thon et mayonnaise.","De klassieker, met tonijn en mayo.","Класика — з тунцем і майонезом.")),
        it("5,80", [],
           M("Setas al ajillo","Garlic mushrooms","Pilze in Knoblauch","Champignons à l'ail","Knoflookchampignons","Гриби в часнику"),
           M("Salteadas con ajo y aceite de oliva.","Sautéed with garlic and olive oil.","In Knoblauch und Olivenöl gebraten.","Sautées à l'ail et huile d'olive.","Gebakken met knoflook en olijfolie.","Смажені з часником та оливковою олією.")),
        it("6,80", ["gluten","lacteos"],
           M("Nachos con guacamole","Nachos with guacamole","Nachos mit Guacamole","Nachos au guacamole","Nacho's met guacamole","Начос з гуакамоле"),
           M("Con guacamole, tomate y cheddar.","With guacamole, tomato and cheddar.","Mit Guacamole, Tomate und Cheddar.","Guacamole, tomate et cheddar.","Met guacamole, tomaat en cheddar.","З гуакамоле, томатом і чедером."), pop=True),
        it("6,80", ["gluten"],
           M("Hummus con picos","Hummus with breadsticks","Hummus mit Brotsticks","Houmous et gressins","Hummus met broodstengels","Хумус із паличками"),
           M("Hummus de garbanzo con picos de pan.","Chickpea hummus with bread sticks.","Kichererbsen-Hummus mit Brotsticks.","Houmous de pois chiches et gressins.","Kikkererwtenhummus met broodstengels.","Хумус із нуту з хлібними паличками.")),
        it("3,50", ["huevo"],
           M("Tortilla","Spanish omelette","Tortilla","Tortilla","Tortilla","Тортилья"),
           M("Tortilla de patata tradicional.","Traditional potato omelette.","Traditionelle Kartoffel-Tortilla.","Tortilla de pommes de terre.","Traditionele aardappelomelet.","Традиційна картопляна тортилья.")),
        it("4,50", ["gluten","pescado","lacteos"],
           M("Croquetas de bacalao (3 u.)","Cod croquettes (3 pcs)","Kabeljau-Kroketten (3 St.)","Croquettes de morue (3 pc)","Kabeljauwkroketten (3 st.)","Крокети з тріски (3 шт.)"),
           M("Cremosas, rebozadas y fritas.","Creamy, breaded and fried.","Cremig, paniert und frittiert.","Crémeuses, panées et frites.","Romig, gepaneerd en gebakken.","Кремові, в паніровці, смажені.")),
        it("4,50", ["gluten","lacteos"],
           M("Croquetas de jamón ibérico (3 u.)","Iberian ham croquettes (3 pcs)","Iberico-Schinken-Kroketten (3 St.)","Croquettes de jambon ibérique (3 pc)","Iberische ham kroketten (3 st.)","Крокети з іберійською шинкою (3 шт.)"),
           M("El clásico del bar, cremosas por dentro.","The bar classic, creamy inside.","Der Bar-Klassiker, innen cremig.","Le classique du bar, crémeuses.","De barklassieker, romig vanbinnen.","Класика бару, кремові всередині."), pop=True),
        it("9,50", ["huevo","crustaceos"],
           M("Revuelto mar y tierra","Surf & turf scramble","Rührei „Meer & Land\"","Œufs brouillés mer et terre","Roerei zee en land","Яєчня 'море й суша'"),
           M("Champiñones, setas, gambas, ajetes y espárragos.","Mushrooms, shrimp, garlic shoots and asparagus.","Champignons, Garnelen, Knoblauchsprossen und Spargel.","Champignons, crevettes, aillets et asperges.","Champignons, garnalen, knoflookscheuten en asperges.","Гриби, креветки, часникові паростки, спаржа.")),
        it("7,80", ["huevo"],
           M("Revuelto de setas al ajillo","Garlic mushroom scramble","Rührei mit Knoblauchpilzen","Œufs brouillés champignons à l'ail","Roerei met knoflookchampignons","Яєчня з грибами в часнику"),
           M("Huevos revueltos con setas y ajo.","Scrambled eggs with mushrooms and garlic.","Rührei mit Pilzen und Knoblauch.","Œufs brouillés aux champignons et ail.","Roerei met champignons en knoflook.","Яєчня-бовтанка з грибами й часником.")),
        it("7,80", ["huevo"],
           M("Huevos rotos con jamón","Broken eggs with ham","Bauernfrühstück mit Schinken","Œufs cassés au jambon","Gebroken eieren met ham","Яйця з шинкою"),
           M("Con jamón y patatas fritas.","With ham and fries.","Mit Schinken und Pommes.","Avec jambon et frites.","Met ham en friet.","З шинкою та картоплею фрі.")),
        it("4,50", [],
           M("Patatas bravas","Patatas bravas","Patatas bravas","Patatas bravas","Patatas bravas","Пататас бравас"),
           M("Con salsa brava picante.","With spicy brava sauce.","Mit scharfer Brava-Soße.","Sauce brava épicée.","Met pittige bravasaus.","З гострим соусом брава.")),
        it("3,50", ["pescado"],
           M("Patatas chips con boquerones","Crisps with anchovies","Chips mit Sardellen","Chips aux anchois","Chips met ansjovis","Чипси з анчоусами"),
           M("Boquerones en vinagre sobre patatas.","Vinegar anchovies over crisps.","Sardellen in Essig auf Chips.","Anchois au vinaigre sur chips.","Ansjovis in azijn op chips.","Анчоуси в оцті на чипсах.")),
        it("6,00", ["gluten"],
           M("Lágrimas de pollo","Chicken tenders","Hähnchen-Tender","Aiguillettes de poulet","Kiptenders","Курячі смужки"),
           M("Tiras de pollo rebozadas.","Breaded chicken strips.","Panierte Hähnchenstreifen.","Lanières de poulet panées.","Gepaneerde kipreepjes.","Курячі смужки в паніровці.")),
        it("6,50", ["huevo"],
           M("Tortilla con ensalada y verdura","Omelette with salad","Tortilla mit Salat","Tortilla avec salade","Tortilla met salade","Тортилья із салатом"),
           M("Tortilla acompañada de ensalada.","Omelette served with salad.","Tortilla mit Salat serviert.","Tortilla servie avec salade.","Tortilla geserveerd met salade.","Тортилья в супроводі салату.")),
        it("3,80", [],
           M("Patatas fritas","Fries","Pommes frites","Frites","Friet","Картопля фрі"),
           M("Ración de patatas fritas.","A portion of fries.","Eine Portion Pommes.","Une portion de frites.","Een portie friet.","Порція картоплі фрі.")),
    ])

# ============ ESPECIALES DE PIZARRA (крейдяна дошка — фірмові) ============
sec("pizarra",
    M("Especiales de pizarra","Chalkboard specials","Tafel-Spezialitäten","Spécialités à l'ardoise","Krijtbord-specials","Фірмові з дошки"),
    M("Nuestras sugerencias del día.","Our daily suggestions.","Unsere Tagesempfehlungen.","Nos suggestions du jour.","Onze dagsuggesties.","Наші пропозиції дня."),
    [
        it("3,50", ["gluten","lacteos"],
           M("Focaccia de chorizo o gorgonzola","Focaccia, chorizo or gorgonzola","Focaccia mit Chorizo oder Gorgonzola","Focaccia chorizo ou gorgonzola","Focaccia met chorizo of gorgonzola","Фокача з чорізо або горгонзолою"),
           M("Con bebida (caña o vino de casa) 5,50 €.","With a drink (beer or house wine) €5.50.","Mit Getränk (Bier oder Hauswein) 5,50 €.","Avec boisson (bière ou vin maison) 5,50 €.","Met drankje (bier of huiswijn) € 5,50.","З напоєм (пиво чи домашнє вино) 5,50 €.")),
        it("6,80", ["gluten"],
           M("Wrap de pollo","Chicken wrap","Hähnchen-Wrap","Wrap au poulet","Kipwrap","Ролл з куркою"),
           M("Lechuga, tomate, cebolla, queso y salsa. Opción vegetariana 6,50 €.","Lettuce, tomato, onion, cheese and sauce. Veggie option €6.50.","Salat, Tomate, Zwiebel, Käse und Soße. Vegetarisch 6,50 €.","Laitue, tomate, oignon, fromage et sauce. Végé 6,50 €.","Sla, tomaat, ui, kaas en saus. Vega € 6,50.","Салат, томат, цибуля, сир і соус. Вегетар. 6,50 €.")),
        it("7,50", ["crustaceos","gluten"],
           M("Gambas al ajillo","Garlic prawns","Knoblauchgarnelen","Gambas à l'ail","Knoflookgarnalen","Креветки в часнику"),
           M("Con pan tostado.","With toasted bread.","Mit geröstetem Brot.","Avec pain grillé.","Met geroosterd brood.","З підсмаженим хлібом."), pop=True),
        it("13,80", ["gluten","crustaceos"],
           M("Fettuccine o penne frutos del mar","Seafood fettuccine or penne","Fettuccine oder Penne mit Meeresfrüchten","Fettuccine ou penne aux fruits de mer","Fettuccine of penne met zeevruchten","Феттучіні чи пенне з морепродуктами"),
           M("Pasta con frutos del mar.","Pasta with mixed seafood.","Pasta mit Meeresfrüchten.","Pâtes aux fruits de mer.","Pasta met zeevruchten.","Паста з морепродуктами.")),
        it("8,00", ["gluten","huevo"],
           M("Bocadillo de calamares maxi","Maxi calamari sandwich","Maxi-Tintenfisch-Sandwich","Maxi sandwich de calamars","Maxi calamaris-broodje","Максі-сендвіч з кальмарами"),
           M("Con mayonesa o alioli. Versión normal 5,50 €.","With mayo or aioli. Regular €5.50.","Mit Mayo oder Aioli. Normal 5,50 €.","Mayo ou aïoli. Version normale 5,50 €.","Met mayo of aioli. Normaal € 5,50.","З майонезом чи айолі. Звичайний 5,50 €.")),
        it("9,80", ["gluten","huevo"],
           M("Pasta penne boloñesa","Penne bolognese","Penne Bolognese","Penne bolognaise","Penne bolognese","Пенне болоньєзе"),
           M("Casera, con carne.","Homemade, with meat.","Hausgemacht, mit Fleisch.","Maison, à la viande.","Huisgemaakt, met vlees.","Домашня, з м'ясом.")),
        it("13,80", ["huevo"],
           M("Hamburguesa con huevo ecológico","Burger with organic egg","Burger mit Bio-Ei","Burger à l'œuf bio","Burger met bio-ei","Бургер з органічним яйцем"),
           M("Con patatas o ensalada.","With fries or salad.","Mit Pommes oder Salat.","Avec frites ou salade.","Met friet of salade.","З картоплею або салатом.")),
        it("3,50", ["gluten","huevo"],
           M("Empanadas argentinas caseras","Homemade Argentine empanadas","Hausgemachte argentinische Empanadas","Empanadas argentines maison","Huisgemaakte Argentijnse empanadas","Домашні аргентинські емпанади"),
           M("Carne, jamón y queso, o pollo.","Beef, ham & cheese, or chicken.","Rind, Schinken-Käse oder Hähnchen.","Bœuf, jambon-fromage ou poulet.","Rund, ham-kaas of kip.","М'ясо, шинка з сиром або курка.")),
        it("3,00", ["pescado","gluten"],
           M("Marinera","Marinera roll","Marinera","Marinera","Marinera","Марінера"),
           M("Con anchoa o boquerón.","With anchovy.","Mit Sardelle.","À l'anchois.","Met ansjovis.","З анчоусом.")),
        it("5,00", ["pescado","gluten"],
           M("Matrimonio","„Matrimonio\"","„Matrimonio\"","Matrimonio","Matrimonio","Матрімоніо"),
           M("Anchoa y boquerón juntos.","Anchovy and white anchovy together.","Sardelle und Anchovis zusammen.","Anchois et anchois blanc.","Ansjovis en witte ansjovis.","Анчоус і білий анчоус разом.")),
        it("5,80", [],
           M("Patatas bravioli","Patatas bravioli","Patatas bravioli","Patatas bravioli","Patatas bravioli","Пататас бравіолі"),
           M("Con salsa brava y alioli.","With brava sauce and aioli.","Mit Brava-Soße und Aioli.","Sauce brava et aïoli.","Met bravasaus en aioli.","З соусом брава та айолі.")),
        it("7,20", ["pescado"],
           M("Lata de sardina Ortiz","Ortiz sardine tin","Ortiz-Sardinendose","Boîte de sardines Ortiz","Ortiz-sardienenblik","Сардини Ortiz"),
           M("En aceite de oliva, con pan tostado.","In olive oil, with toasted bread.","In Olivenöl, mit geröstetem Brot.","À l'huile d'olive, pain grillé.","In olijfolie, met geroosterd brood.","В оливковій олії, з тостами.")),
        it("9,50", ["crustaceos"],
           M("Langostino cocido","Cooked king prawns","Gekochte Riesengarnelen","Gambas cuites","Gekookte gamba's","Варені королівські креветки"),
           M("Servido en hielo, con alioli.","Served on ice, with aioli.","Auf Eis serviert, mit Aioli.","Servi sur glace, avec aïoli.","Op ijs geserveerd, met aioli.","На льоду, з айолі.")),
        it("11,00", ["crustaceos"],
           M("Gambón a la plancha","Grilled king prawns","Gegrillte Riesengarnelen","Gambas grillées","Gegrilde gamba's","Королівські креветки на грилі"),
           M("A la plancha, al punto de sal.","Grilled, lightly salted.","Vom Grill, leicht gesalzen.","Grillées, légèrement salées.","Gegrild, licht gezouten.","На грилі, з дрібкою солі."), pop=True),
        it("8,90", ["gluten","lacteos"],
           M("Bruschetta serrano","Serrano bruschetta","Serrano-Bruschetta","Bruschetta serrano","Serrano bruschetta","Брускета з серрано"),
           M("Mozzarella, jamón serrano y rúcula. Versión mozzarella, tomate y albahaca 7,90 €.","Mozzarella, serrano ham and rocket. Mozzarella-tomato-basil version €7.90.","Mozzarella, Serrano-Schinken und Rucola. Variante Mozzarella-Tomate-Basilikum 7,90 €.","Mozzarella, jambon serrano et roquette. Version mozzarella-tomate-basilic 7,90 €.","Mozzarella, serranoham en rucola. Versie mozzarella-tomaat-basilicum € 7,90.","Моцарела, серрано й рукола. Версія моцарела-томат-базилік 7,90 €.")),
        it("6,50", ["gluten","huevo","lacteos"],
           M("Tarta quiche","Quiche","Quiche","Quiche","Quiche","Кіш"),
           M("Con ensalada.","With salad.","Mit Salat.","Avec salade.","Met salade.","Із салатом.")),
    ])

# ============ ENSALADAS ============
sec("ensaladas",
    M("Ensaladas", "Salads", "Salate", "Salades", "Salades", "Салати"),
    EMPTY,
    [
        it("3,00", [],
           M("Verde","Green salad","Grüner Salat","Salade verte","Groene salade","Зелений салат"),
           M("Lechuga y cebolla.","Lettuce and onion.","Salat und Zwiebel.","Laitue et oignon.","Sla en ui.","Салат і цибуля.")),
        it("4,00", [],
           M("Tomate","Tomato salad","Tomatensalat","Salade de tomates","Tomatensalade","Салат з томатів"),
           M("Tomate y cebolla.","Tomato and onion.","Tomate und Zwiebel.","Tomate et oignon.","Tomaat en ui.","Томат і цибуля.")),
        it("7,50", ["pescado"],
           M("Mixta","Mixed salad","Gemischter Salat","Salade mixte","Gemengde salade","Мішаний салат"),
           M("Lechuga, tomate y atún.","Lettuce, tomato and tuna.","Salat, Tomate und Thunfisch.","Laitue, tomate et thon.","Sla, tomaat en tonijn.","Салат, томат і тунець.")),
        it("9,00", ["lacteos"],
           M("Pollo","Chicken salad","Hähnchensalat","Salade de poulet","Kipsalade","Салат з куркою"),
           M("Lechuga, pollo en salsa de nata, setas y cebolla.","Lettuce, chicken in cream sauce, mushrooms and onion.","Salat, Hähnchen in Sahnesoße, Pilze und Zwiebel.","Laitue, poulet sauce crème, champignons et oignon.","Sla, kip in roomsaus, champignons en ui.","Салат, курка у вершковому соусі, гриби, цибуля.")),
        it("9,50", ["pescado"],
           M("Salmón","Salmon salad","Lachssalat","Salade de saumon","Zalmsalade","Салат з лососем"),
           M("Lechuga, aguacate, tomate, cebolla y brotes.","Lettuce, avocado, tomato, onion and sprouts.","Salat, Avocado, Tomate, Zwiebel und Sprossen.","Laitue, avocat, tomate, oignon et pousses.","Sla, avocado, tomaat, ui en scheuten.","Салат, авокадо, томат, цибуля, паростки.")),
        it("8,00", ["lacteos","gluten"],
           M("Queso de cabra","Goat cheese salad","Ziegenkäse-Salat","Salade de chèvre","Geitenkaassalade","Салат з козячим сиром"),
           M("Lechuga, tomate y tostas de queso de cabra fundido.","Lettuce, tomato and melted goat cheese toasts.","Salat, Tomate und Toasts mit geschmolzenem Ziegenkäse.","Laitue, tomate et toasts de chèvre fondu.","Sla, tomaat en toast met gesmolten geitenkaas.","Салат, томат і тости з плавленим козячим сиром.")),
        it("11,00", ["lacteos"],
           M("Mediterránea","Mediterranean salad","Mediterraner Salat","Salade méditerranéenne","Mediterrane salade","Середземноморський салат"),
           M("Lechuga, tomate, mozzarella, serrano y albahaca.","Lettuce, tomato, mozzarella, serrano and basil.","Salat, Tomate, Mozzarella, Serrano und Basilikum.","Laitue, tomate, mozzarella, serrano et basilic.","Sla, tomaat, mozzarella, serrano en basilicum.","Салат, томат, моцарела, серрано, базилік.")),
        it("11,00", ["huevo"],
           M("Popeye","Popeye salad","Popeye-Salat","Salade Popeye","Popeye-salade","Салат Попай"),
           M("Espinaca, setas, tomate, bacon, huevo revuelto y vinagreta cremosa.","Spinach, mushrooms, tomato, bacon, scrambled egg and creamy vinaigrette.","Spinat, Pilze, Tomate, Speck, Rührei und cremige Vinaigrette.","Épinards, champignons, tomate, bacon, œuf brouillé et vinaigrette crémeuse.","Spinazie, champignons, tomaat, bacon, roerei en romige vinaigrette.","Шпинат, гриби, томат, бекон, яєчня та кремовий вінегрет.")),
    ])

# ============ TOSTAS PAN CRISTAL ============
sec("tostas",
    M("Tostas de pan cristal","Crystal bread toasts","Cristal-Brot-Toasts","Tartines pan cristal","Pan cristal toasts","Тости на пан-крісталь"),
    M("Acompañadas de ensalada de verdura.","Served with a green salad.","Mit grünem Salat serviert.","Servies avec salade verte.","Geserveerd met groene salade.","У супроводі овочевого салату."),
    [
        it("9,80", ["gluten","pescado","lacteos"],
           M("Salmón","Salmon toast","Lachs-Toast","Tartine saumon","Zalmtoast","Тост з лососем"),
           M("Salmón, aguacate, queso fresco y guacamole.","Salmon, avocado, fresh cheese and guacamole.","Lachs, Avocado, Frischkäse und Guacamole.","Saumon, avocat, fromage frais et guacamole.","Zalm, avocado, verse kaas en guacamole.","Лосось, авокадо, свіжий сир і гуакамоле.")),
        it("9,80", ["gluten","lacteos"],
           M("Pollo","Chicken toast","Hähnchen-Toast","Tartine poulet","Kiptoast","Тост з куркою"),
           M("Pollo, salsa de nata, setas y cebolla.","Chicken, cream sauce, mushrooms and onion.","Hähnchen, Sahnesoße, Pilze und Zwiebel.","Poulet, sauce crème, champignons et oignon.","Kip, roomsaus, champignons en ui.","Курка, вершковий соус, гриби, цибуля.")),
        it("8,50", ["gluten","lacteos"],
           M("Ibérica","Iberian toast","Iberischer Toast","Tartine ibérique","Iberische toast","Іберійський тост"),
           M("Tomate rallado, jamón serrano y manchego.","Grated tomato, serrano ham and manchego.","Geriebene Tomate, Serrano-Schinken und Manchego.","Tomate râpée, jambon serrano et manchego.","Geraspte tomaat, serranoham en manchego.","Терті томати, серрано й манчего.")),
    ])

# ============ PASTA ============
sec("pasta",
    M("Pasta", "Pasta", "Pasta", "Pâtes", "Pasta", "Паста"),
    EMPTY,
    [
        it("10,90", ["gluten","lacteos"],
           M("Penne gorgonzola","Penne gorgonzola","Penne Gorgonzola","Penne gorgonzola","Penne gorgonzola","Пенне горгонзола"),
           M("En salsa cremosa de queso gorgonzola y champiñones.","In a creamy gorgonzola and mushroom sauce.","In cremiger Gorgonzola-Pilz-Soße.","Sauce crémeuse gorgonzola et champignons.","In romige gorgonzola-champignonsaus.","У вершковому соусі з горгонзолою та печерицями.")),
        it("11,90", ["gluten","lacteos"],
           M("Penne pollo","Chicken penne","Penne mit Hähnchen","Penne au poulet","Penne met kip","Пенне з куркою"),
           M("Pollo, champiñones y cebolla en salsa cremosa de nata.","Chicken, mushrooms and onion in a creamy sauce.","Hähnchen, Champignons und Zwiebel in Sahnesoße.","Poulet, champignons et oignon, sauce crème.","Kip, champignons en ui in roomsaus.","Курка, печериці й цибуля у вершковому соусі.")),
    ])

# ============ TABLAS ============
sec("tablas",
    M("Tablas", "Sharing boards", "Platten", "Planches", "Plankjes", "Дошки для компанії"),
    M("Para compartir.", "To share.", "Zum Teilen.", "À partager.", "Om te delen.", "Щоб ділитися."),
    [
        it("12,00", ["lacteos","gluten"],
           M("Tabla de quesos","Cheese board","Käseplatte","Planche de fromages","Kaasplank","Сирна дошка"),
           M("Manchego, brie, gorgonzola, mozzarella y pan.","Manchego, brie, gorgonzola, mozzarella and bread.","Manchego, Brie, Gorgonzola, Mozzarella und Brot.","Manchego, brie, gorgonzola, mozzarella et pain.","Manchego, brie, gorgonzola, mozzarella en brood.","Манчего, брі, горгонзола, моцарела і хліб.")),
        it("14,00", ["gluten"],
           M("Tabla de charcutería","Charcuterie board","Wurstplatte","Planche de charcuterie","Vleeswarenplank","М'ясна дошка"),
           M("Jamón, chorizo ibérico, lomo y pan.","Ham, Iberian chorizo, loin and bread.","Schinken, iberische Chorizo, Lende und Brot.","Jambon, chorizo ibérique, longe et pain.","Ham, Iberische chorizo, lende en brood.","Шинка, іберійське чорізо, філе й хліб.")),
        it("8,80", ["gluten"],
           M("Jamón serrano","Serrano ham board","Serrano-Schinken","Jambon serrano","Serranoham","Серрано"),
           M("Queso curado y pan.","Cured cheese and bread.","Gereifter Käse und Brot.","Fromage affiné et pain.","Belegen kaas en brood.","Витриманий сир і хліб.")),
        it("8,80", [],
           M("Melón con jamón","Melon with ham","Melone mit Schinken","Melon au jambon","Meloen met ham","Диня з шинкою"),
           M("Melón con jamón serrano.","Melon with serrano ham.","Melone mit Serrano-Schinken.","Melon au jambon serrano.","Meloen met serranoham.","Диня з шинкою серрано.")),
        it("19,00", ["gluten","lacteos","pescado","huevo"],
           M("Tabla XL","XL board","XL-Platte","Planche XL","XL-plank","Дошка XL"),
           M("Charcutería, queso, queso fresco, salmón, ensaladilla, aguacate y pan.","Charcuterie, cheese, fresh cheese, salmon, Russian salad, avocado and bread.","Wurst, Käse, Frischkäse, Lachs, russischer Salat, Avocado und Brot.","Charcuterie, fromage, fromage frais, saumon, salade russe, avocat et pain.","Vleeswaren, kaas, verse kaas, zalm, Russische salade, avocado en brood.","Ковбаси, сир, свіжий сир, лосось, олів'є, авокадо і хліб."), pop=True),
    ])

# ============ BOCADILLOS ============
sec("bocadillos",
    M("Bocadillos", "Sandwiches", "Sandwiches", "Sandwichs", "Broodjes", "Сендвічі"),
    EMPTY,
    [
        it("4,80", ["gluten","lacteos"],
           M("Italiano","Italian","Italiano","Italien","Italiaans","Італійський"),
           M("Tomate, mozzarella y albahaca.","Tomato, mozzarella and basil.","Tomate, Mozzarella und Basilikum.","Tomate, mozzarella et basilic.","Tomaat, mozzarella en basilicum.","Томат, моцарела і базилік.")),
        it("4,50", ["gluten","huevo","pescado"],
           M("Atún","Tuna","Thunfisch","Thon","Tonijn","Тунець"),
           M("Mayonesa, tomate y cebolla.","Mayo, tomato and onion.","Mayo, Tomate und Zwiebel.","Mayo, tomate et oignon.","Mayo, tomaat en ui.","Майонез, томат і цибуля.")),
        it("4,50", ["gluten","lacteos"],
           M("Jamón serrano","Serrano ham","Serrano-Schinken","Jambon serrano","Serranoham","Серрано"),
           M("Tomate rallado y queso.","Grated tomato and cheese.","Geriebene Tomate und Käse.","Tomate râpée et fromage.","Geraspte tomaat en kaas.","Терті томати і сир.")),
        it("4,80", ["gluten","lacteos"],
           M("Pollo","Chicken","Hähnchen","Poulet","Kip","Курка"),
           M("Champiñones, cebolla y salsa de nata.","Mushrooms, onion and cream sauce.","Champignons, Zwiebel und Sahnesoße.","Champignons, oignon et sauce crème.","Champignons, ui en roomsaus.","Печериці, цибуля і вершковий соус.")),
        it("4,50", ["gluten","huevo"],
           M("Tortilla","Omelette","Tortilla","Tortilla","Tortilla","Тортилья"),
           M("Con tomate rallado.","With grated tomato.","Mit geriebener Tomate.","Avec tomate râpée.","Met geraspte tomaat.","З тертим томатом.")),
        it("7,80", ["gluten"],
           M("Americano","American","Americano","Américain","Amerikaans","Американський"),
           M("Hamburguesa, patatas fritas y ketchup.","Burger, fries and ketchup.","Burger, Pommes und Ketchup.","Burger, frites et ketchup.","Burger, friet en ketchup.","Бургер, картопля фрі й кетчуп.")),
        it("6,80", ["gluten","pescado","lacteos"],
           M("Salmón","Salmon","Lachs","Saumon","Zalm","Лосось"),
           M("Pan integral, aguacate, guacamole y queso fresco.","Wholemeal bread, avocado, guacamole and fresh cheese.","Vollkornbrot, Avocado, Guacamole und Frischkäse.","Pain complet, avocat, guacamole et fromage frais.","Volkorenbrood, avocado, guacamole en verse kaas.","Цільнозерновий хліб, авокадо, гуакамоле, свіжий сир.")),
    ])

# ============ HAMBURGUESAS ============
sec("burgers",
    M("Hamburguesas", "Burgers", "Burger", "Burgers", "Burgers", "Бургери"),
    EMPTY,
    [
        it("10,00", ["gluten"],
           M("Burger vegetariana","Veggie burger","Veggie-Burger","Burger végétarien","Vegaburger","Вегетаріанський бургер"),
           M("Hamburguesa vegetal.","Plant-based burger.","Pflanzlicher Burger.","Burger végétal.","Plantaardige burger.","Рослинний бургер.")),
        it("12,00", ["gluten"],
           M("Burger vegetariana con patatas","Veggie burger with fries","Veggie-Burger mit Pommes","Burger végé avec frites","Vegaburger met friet","Вегетаріанський бургер з фрі"),
           M("Con patatas fritas.","With fries.","Mit Pommes.","Avec frites.","Met friet.","З картоплею фрі.")),
        it("10,50", ["gluten"],
           M("Burger de vacuno","Beef burger","Rindfleisch-Burger","Burger de bœuf","Runderburger","Яловичий бургер"),
           M("Carne de vacuno.","Beef patty.","Rindfleisch-Patty.","Steak haché de bœuf.","Rundvleesburger.","Котлета з яловичини."), pop=True),
        it("12,50", ["gluten"],
           M("Burger de vacuno con patatas","Beef burger with fries","Rindfleisch-Burger mit Pommes","Burger de bœuf avec frites","Runderburger met friet","Яловичий бургер з фрі"),
           M("Con patatas fritas.","With fries.","Mit Pommes.","Avec frites.","Met friet.","З картоплею фрі.")),
    ])

# ============ CREPES ============
sec("crepes",
    M("Crepes", "Crêpes", "Crêpes", "Crêpes", "Crêpes", "Млинці"),
    EMPTY,
    [
        it("7,80", ["gluten","huevo","lacteos"],
           M("La completa","„La completa\"","La completa","La completa","La completa","Ла комплета"),
           M("Jamón york, huevo y queso.","Cooked ham, egg and cheese.","Kochschinken, Ei und Käse.","Jambon, œuf et fromage.","Ham, ei en kaas.","Шинка, яйце і сир.")),
        it("10,00", ["gluten","huevo","pescado","lacteos"],
           M("La salmón","„La salmón\"","La salmón","La saumon","La zalm","Ла лосось"),
           M("Salmón ahumado, guacamole, queso fresco y aguacate.","Smoked salmon, guacamole, fresh cheese and avocado.","Räucherlachs, Guacamole, Frischkäse und Avocado.","Saumon fumé, guacamole, fromage frais et avocat.","Gerookte zalm, guacamole, verse kaas en avocado.","Копчений лосось, гуакамоле, свіжий сир, авокадо.")),
        it("9,00", ["gluten","huevo","lacteos"],
           M("La campesina","„La campesina\"","La campesina","La campagnarde","La campesina","Ла кампесіна"),
           M("Pollo, setas, nata y cebolla.","Chicken, mushrooms, cream and onion.","Hähnchen, Pilze, Sahne und Zwiebel.","Poulet, champignons, crème et oignon.","Kip, champignons, room en ui.","Курка, гриби, вершки й цибуля.")),
        it("8,50", ["gluten","huevo","lacteos"],
           M("La carlitos","„La carlitos\"","La carlitos","La carlitos","La carlitos","Ла карлітос"),
           M("Mozzarella, tomate y aceite de albahaca.","Mozzarella, tomato and basil oil.","Mozzarella, Tomate und Basilikumöl.","Mozzarella, tomate et huile de basilic.","Mozzarella, tomaat en basilicumolie.","Моцарела, томат і базилікова олія.")),
        it("3,50", ["gluten","huevo"],
           M("Crepe de azúcar","Sugar crêpe","Zucker-Crêpe","Crêpe au sucre","Suikercrêpe","Млинець із цукром"),
           M("Sencilla, con azúcar.","Simple, with sugar.","Einfach, mit Zucker.","Simple, au sucre.","Eenvoudig, met suiker.","Простий, із цукром.")),
        it("4,00", ["gluten","huevo","lacteos","frutos"],
           M("Crepe de Nutella","Nutella crêpe","Nutella-Crêpe","Crêpe Nutella","Nutella-crêpe","Млинець з Нутеллою"),
           M("Con crema de avellanas y cacao.","With hazelnut-cocoa spread.","Mit Haselnuss-Kakao-Creme.","À la pâte noisette-cacao.","Met hazelnoot-cacaopasta.","З горіхово-какао пастою.")),
        it("4,00", ["gluten","huevo","lacteos"],
           M("Crepe de dulce de leche","Dulce de leche crêpe","Dulce-de-Leche-Crêpe","Crêpe dulce de leche","Dulce de leche-crêpe","Млинець з дульсе де лече"),
           M("Con dulce de leche.","With dulce de leche.","Mit Dulce de Leche.","Au dulce de leche.","Met dulce de leche.","З вареним згущеним молоком.")),
        it("5,50", ["gluten","huevo","lacteos"],
           M("Crepe de chocolate y plátano","Chocolate-banana crêpe","Schoko-Bananen-Crêpe","Crêpe chocolat-banane","Chocolade-banaan-crêpe","Млинець з шоколадом і бананом"),
           M("Chocolate y plátano.","Chocolate and banana.","Schokolade und Banane.","Chocolat et banane.","Chocolade en banaan.","Шоколад і банан.")),
        it("5,50", ["gluten","huevo","lacteos"],
           M("Crepe con helado y nata","Crêpe with ice cream & cream","Crêpe mit Eis und Sahne","Crêpe glace et chantilly","Crêpe met ijs en slagroom","Млинець з морозивом і вершками"),
           M("Helado con nata.","Ice cream with cream.","Eis mit Sahne.","Glace et chantilly.","IJs met slagroom.","Морозиво з вершками.")),
    ])

# ============ POSTRES Y HELADOS ============
sec("postres",
    M("Postres y helados", "Desserts & ice cream", "Desserts & Eis", "Desserts & glaces", "Desserts & ijs", "Десерти й морозиво"),
    EMPTY,
    [
        it("6,00", [],
           M("Plato de fruta fresca","Fresh fruit plate","Frischer Obstteller","Assiette de fruits frais","Vers fruitbord","Тарілка свіжих фруктів"),
           M("Selección de fruta de temporada.","A selection of seasonal fruit.","Auswahl an Saisonobst.","Sélection de fruits de saison.","Selectie van seizoensfruit.","Добірка сезонних фруктів.")),
        it("5,80", ["lacteos","huevo","frutos"],
           M("Banana split","Banana split","Banana Split","Banana split","Bananasplit","Банана спліт"),
           M("Plátano, helado y nata.","Banana, ice cream and cream.","Banane, Eis und Sahne.","Banane, glace et chantilly.","Banaan, ijs en slagroom.","Банан, морозиво і вершки.")),
        it("4,90", ["lacteos","huevo"],
           M("Café liégeois","Café liégeois","Café Liégeois","Café liégeois","Café liégeois","Кава ліжуа"),
           M("Café, helado de café y nata.","Coffee, coffee ice cream and cream.","Kaffee, Kaffee-Eis und Sahne.","Café, glace café et chantilly.","Koffie, koffie-ijs en slagroom.","Кава, кавове морозиво і вершки.")),
        it("4,90", ["lacteos","huevo"],
           M("Chocolat liégeois","Chocolat liégeois","Schokoladen-Liégeois","Chocolat liégeois","Chocolat liégeois","Шоколад ліжуа"),
           M("Chocolate, helado y nata.","Chocolate, ice cream and cream.","Schokolade, Eis und Sahne.","Chocolat, glace et chantilly.","Chocolade, ijs en slagroom.","Шоколад, морозиво і вершки.")),
        it("4,90", ["lacteos","huevo"],
           M("Dame blanche","Dame blanche","Dame Blanche","Dame blanche","Dame blanche","Дам бланш"),
           M("Helado de vainilla con chocolate caliente y nata.","Vanilla ice cream with hot chocolate and cream.","Vanilleeis mit heißer Schokolade und Sahne.","Glace vanille, chocolat chaud et chantilly.","Vanille-ijs met warme chocolade en slagroom.","Ванільне морозиво з гарячим шоколадом і вершками.")),
        it("2,50", ["lacteos","huevo"],
           M("Helado (1 bola)","Ice cream (1 scoop)","Eis (1 Kugel)","Glace (1 boule)","IJs (1 bol)","Морозиво (1 кулька)"),
           M("Ver sabores. 2 bolas 3,50 € · 3 bolas 4,50 €.","See flavours. 2 scoops €3.50 · 3 scoops €4.50.","Sorten siehe Tafel. 2 Kugeln 3,50 € · 3 Kugeln 4,50 €.","Voir parfums. 2 boules 3,50 € · 3 boules 4,50 €.","Zie smaken. 2 bollen € 3,50 · 3 bollen € 4,50.","Смаки на дошці. 2 кульки 3,50 € · 3 кульки 4,50 €.")),
    ])

# ============ BATIDOS, GRANIZADOS Y ZUMOS ============
sec("batidos",
    M("Batidos, granizados y zumos", "Shakes, slushies & juices", "Shakes, Slush & Säfte", "Milkshakes, granités & jus", "Shakes, slush & sappen", "Шейки, гранізадо й соки"),
    EMPTY,
    [
        it("3,50", [],
           M("Granizado","Slushie","Slush","Granité","Granita","Гранізадо"),
           M("Limón, fresa, mango o café.","Lemon, strawberry, mango or coffee.","Zitrone, Erdbeere, Mango oder Kaffee.","Citron, fraise, mangue ou café.","Citroen, aardbei, mango of koffie.","Лимон, полуниця, манго чи кава.")),
        it("5,50", ["lacteos"],
           M("Blanco y negro","„Blanco y negro\"","Blanco y Negro","Blanco y negro","Blanco y negro","Бланко і неґро"),
           M("Granizado de café con una bola de helado.","Coffee slushie with a scoop of ice cream.","Kaffee-Slush mit einer Kugel Eis.","Granité de café avec une boule de glace.","Koffieslush met een bol ijs.","Кавове гранізадо з кулькою морозива.")),
        it("3,80", [],
           M("Smoothie","Smoothie","Smoothie","Smoothie","Smoothie","Смузі"),
           M("Fresa, frutos rojos, mango o arándanos.","Strawberry, red berries, mango or blueberry.","Erdbeere, rote Beeren, Mango oder Heidelbeere.","Fraise, fruits rouges, mangue ou myrtille.","Aardbei, rode vruchten, mango of bosbes.","Полуниця, червоні ягоди, манго чи чорниця.")),
        it("3,80", [],
           M("Zumo multivitamina","Multivitamin juice","Multivitaminsaft","Jus multivitaminé","Multivitaminesap","Мультивітамінний сік"),
           M("Zumo natural de frutas.","Natural fruit juice.","Natürlicher Fruchtsaft.","Jus de fruits naturel.","Natuurlijk vruchtensap.","Натуральний фруктовий сік.")),
        it("4,00", ["lacteos"],
           M("Milkshake","Milkshake","Milchshake","Milkshake","Milkshake","Мілкшейк"),
           M("Fresa, chocolate, vainilla, cookies, turrón o dulce de leche. Leche animal o vegetal.","Strawberry, chocolate, vanilla, cookies, turrón or dulce de leche. Dairy or plant milk.","Erdbeere, Schoko, Vanille, Cookies, Turrón oder Dulce de Leche. Tier- oder Pflanzenmilch.","Fraise, chocolat, vanille, cookies, turrón ou dulce de leche. Lait animal ou végétal.","Aardbei, chocolade, vanille, koekjes, turrón of dulce de leche. Dierlijke of plantaardige melk.","Полуниця, шоколад, ваніль, печиво, туррон чи дульсе де лече. Тваринне або рослинне молоко.")),
        it("3,50", [],
           M("Horchata","Horchata","Horchata","Horchata","Horchata","Орчата"),
           M("Bebida de chufa, bien fría.","Chilled tiger nut drink.","Erfrischendes Erdmandelgetränk.","Boisson de souchet, bien fraîche.","Verfrissende chufadrank.","Прохолодний напій із чуфи.")),
    ])

# ============ BEBIDAS ============
sec("bebidas",
    M("Bebidas", "Drinks", "Getränke", "Boissons", "Dranken", "Напої"),
    EMPTY,
    [
        it("1,70", [],
           M("Agua","Water","Wasser","Eau","Water","Вода"),
           M("Pequeña 1,70 € · grande 2,50 € · con gas 2,30 €.","Small €1.70 · large €2.50 · sparkling €2.30.","Klein 1,70 € · groß 2,50 € · mit Kohlensäure 2,30 €.","Petite 1,70 € · grande 2,50 € · gazeuse 2,30 €.","Klein € 1,70 · groot € 2,50 · bruisend € 2,30.","Мала 1,70 € · велика 2,50 € · газована 2,30 €.")),
        it("2,30", [],
           M("Refrescos","Soft drinks","Erfrischungsgetränke","Sodas","Frisdranken","Безалкогольні"),
           M("Coca-Cola, Fanta, Sprite, Nestea, Aquarius, tónica.","Coca-Cola, Fanta, Sprite, Nestea, Aquarius, tonic.","Coca-Cola, Fanta, Sprite, Nestea, Aquarius, Tonic.","Coca-Cola, Fanta, Sprite, Nestea, Aquarius, tonic.","Coca-Cola, Fanta, Sprite, Nestea, Aquarius, tonic.","Coca-Cola, Fanta, Sprite, Nestea, Aquarius, тонік.")),
        it("3,50", [],
           M("Red Bull","Red Bull","Red Bull","Red Bull","Red Bull","Red Bull"),
           M("Bebida energética.","Energy drink.","Energydrink.","Boisson énergisante.","Energiedrank.","Енергетик.")),
        it("2,40", ["gluten"],
           M("Caña o clara","Small beer","Kleines Bier","Demi","Klein bier","Мале пиво"),
           M("Cerveza de barril. Pinta 4,40 €.","Draft beer. Pint €4.40.","Bier vom Fass. Pint 4,40 €.","Bière pression. Pinte 4,40 €.","Bier van het vat. Pint € 4,40.","Розливне пиво. Пінта 4,40 €.")),
        it("2,90", ["gluten"],
           M("Cerveza botella","Bottled beer","Flaschenbier","Bière bouteille","Flesbier","Пиво пляшкове"),
           M("Mahou, sin alcohol, tostada o sin gluten. Alhambra, Corona, IPA, Paulaner o Leffe hasta 4,50 €.","Mahou, alcohol-free, toasted or gluten-free. Alhambra, Corona, IPA, Paulaner or Leffe up to €4.50.","Mahou, alkoholfrei, Tostada oder glutenfrei. Alhambra, Corona, IPA, Paulaner oder Leffe bis 4,50 €.","Mahou, sans alcool, tostada ou sans gluten. Alhambra, Corona, IPA, Paulaner ou Leffe jusqu'à 4,50 €.","Mahou, alcoholvrij, tostada of glutenvrij. Alhambra, Corona, IPA, Paulaner of Leffe tot € 4,50.","Mahou, безалкогольне, тостада чи безглютенове. Alhambra, Corona, IPA, Paulaner чи Leffe до 4,50 €.")),
        it("3,00", ["sulfitos"],
           M("Vino de la casa","House wine","Hauswein","Vin maison","Huiswijn","Домашнє вино"),
           M("Tinto, blanco o rosado. Copa 3,00 € · botella desde 15,00 €.","Red, white or rosé. Glass €3.00 · bottle from €15.00.","Rot, weiß oder rosé. Glas 3,00 € · Flasche ab 15,00 €.","Rouge, blanc ou rosé. Verre 3,00 € · bouteille dès 15,00 €.","Rood, wit of rosé. Glas € 3,00 · fles vanaf € 15,00.","Червоне, біле чи рожеве. Келих 3,00 € · пляшка від 15,00 €.")),
        it("3,20", ["sulfitos"],
           M("Tinto de verano","Tinto de verano","Tinto de Verano","Tinto de verano","Tinto de verano","Тінто де верано"),
           M("Vino tinto con gaseosa.","Red wine with lemon soda.","Rotwein mit Limonade.","Vin rouge et limonade.","Rode wijn met limonade.","Червоне вино з лимонадом.")),
        it("4,40", ["sulfitos"],
           M("Sangría","Sangria","Sangria","Sangria","Sangria","Сангрія"),
           M("La de siempre, por copa o jarra.","The classic, by glass or jug.","Der Klassiker, Glas oder Karaffe.","La classique, au verre ou en pichet.","De klassieker, per glas of kan.","Класика, келих або глек.")),
        it("6,50", [],
           M("Ginebra","Gin","Gin","Gin","Gin","Джин"),
           M("Larios, Seagram's, Beefeater, Tanqueray, Puerto de Indias o Martin Miller's.","Larios, Seagram's, Beefeater, Tanqueray, Puerto de Indias or Martin Miller's.","Larios, Seagram's, Beefeater, Tanqueray, Puerto de Indias oder Martin Miller's.","Larios, Seagram's, Beefeater, Tanqueray, Puerto de Indias ou Martin Miller's.","Larios, Seagram's, Beefeater, Tanqueray, Puerto de Indias of Martin Miller's.","Larios, Seagram's, Beefeater, Tanqueray, Puerto de Indias чи Martin Miller's.")),
        it("5,50", [],
           M("Ron","Rum","Rum","Rhum","Rum","Ром"),
           M("Cacique, Santa Teresa, Bacardí, Brugal, Barceló, Matusalem o Zacapa.","Cacique, Santa Teresa, Bacardí, Brugal, Barceló, Matusalem or Zacapa.","Cacique, Santa Teresa, Bacardí, Brugal, Barceló, Matusalem oder Zacapa.","Cacique, Santa Teresa, Bacardí, Brugal, Barceló, Matusalem ou Zacapa.","Cacique, Santa Teresa, Bacardí, Brugal, Barceló, Matusalem of Zacapa.","Cacique, Santa Teresa, Bacardí, Brugal, Barceló, Matusalem чи Zacapa.")),
        it("6,00", [],
           M("Whisky","Whisky","Whisky","Whisky","Whisky","Віскі"),
           M("J&B, Jameson, Johnnie Walker, Ballantine's o Cardhu.","J&B, Jameson, Johnnie Walker, Ballantine's or Cardhu.","J&B, Jameson, Johnnie Walker, Ballantine's oder Cardhu.","J&B, Jameson, Johnnie Walker, Ballantine's ou Cardhu.","J&B, Jameson, Johnnie Walker, Ballantine's of Cardhu.","J&B, Jameson, Johnnie Walker, Ballantine's чи Cardhu.")),
        it("4,00", [],
           M("Licores","Liqueurs","Liköre","Liqueurs","Likeuren","Лікери"),
           M("Martini, brandy, Bailey's, Ricard, orujo, limoncello o chupito.","Martini, brandy, Bailey's, Ricard, orujo, limoncello or shot.","Martini, Brandy, Bailey's, Ricard, Orujo, Limoncello oder Shot.","Martini, brandy, Bailey's, Ricard, orujo, limoncello ou shot.","Martini, brandy, Bailey's, Ricard, orujo, limoncello of shotje.","Martini, бренді, Bailey's, Ricard, орухо, лімончело чи чарка.")),
    ])

# ============ CÓCTELES ============
sec("cocteles",
    M("Cócteles", "Cocktails", "Cocktails", "Cocktails", "Cocktails", "Коктейлі"),
    EMPTY,
    [
        it("7,00", [],
           M("Sex on the beach","Sex on the Beach","Sex on the Beach","Sex on the Beach","Sex on the Beach","Sex on the Beach"),
           M("Vodka, melocotón y frutas.","Vodka, peach and fruit.","Wodka, Pfirsich und Früchte.","Vodka, pêche et fruits.","Wodka, perzik en fruit.","Горілка, персик і фрукти.")),
        it("6,50", [],
           M("Mojito","Mojito","Mojito","Mojito","Mojito","Мохіто"),
           M("Con ron, lima y menta. Sin alcohol 3,80 €.","With rum, lime and mint. Non-alcoholic €3.80.","Mit Rum, Limette und Minze. Alkoholfrei 3,80 €.","Rhum, citron vert et menthe. Sans alcool 3,80 €.","Met rum, limoen en munt. Alcoholvrij € 3,80.","З ромом, лаймом і м'ятою. Безалкогольний 3,80 €."), pop=True),
        it("6,50", [],
           M("Aperol Spritz","Aperol Spritz","Aperol Spritz","Aperol Spritz","Aperol Spritz","Апероль Шпріц"),
           M("Aperol, cava y soda.","Aperol, cava and soda.","Aperol, Cava und Soda.","Aperol, cava et soda.","Aperol, cava en soda.","Апероль, кава і сода.")),
        it("8,00", ["frutos","lacteos"],
           M("Piña colada","Piña colada","Piña Colada","Piña colada","Piña colada","Піна колада"),
           M("Ron, piña y coco.","Rum, pineapple and coconut.","Rum, Ananas und Kokos.","Rhum, ananas et coco.","Rum, ananas en kokos.","Ром, ананас і кокос.")),
        it("7,00", [],
           M("Negroni","Negroni","Negroni","Negroni","Negroni","Негроні"),
           M("Ginebra, Campari y vermut.","Gin, Campari and vermouth.","Gin, Campari und Wermut.","Gin, Campari et vermouth.","Gin, Campari en vermout.","Джин, Кампарі й вермут.")),
        it("8,00", [],
           M("Caipiriña","Caipirinha","Caipirinha","Caïpirinha","Caipirinha","Кайпіринья"),
           M("Cachaça, lima y azúcar.","Cachaça, lime and sugar.","Cachaça, Limette und Zucker.","Cachaça, citron vert et sucre.","Cachaça, limoen en suiker.","Кашаса, лайм і цукор.")),
    ])

# ============ CAFÉS ============
sec("cafes",
    M("Cafés", "Coffee", "Kaffee", "Cafés", "Koffie", "Кава"),
    EMPTY,
    [
        it("2,50", ["lacteos"],
           M("Iced coffee","Iced coffee","Eiskaffee","Café glacé","IJskoffie","Айс-кава"),
           M("Café frío con hielo.","Cold coffee over ice.","Kalter Kaffee auf Eis.","Café froid sur glace.","Koude koffie op ijs.","Холодна кава з льодом.")),
        it("4,50", ["lacteos"],
           M("Frappuccino","Frappuccino","Frappuccino","Frappuccino","Frappuccino","Фрапучино"),
           M("Vainilla o chocolate.","Vanilla or chocolate.","Vanille oder Schokolade.","Vanille ou chocolat.","Vanille of chocolade.","Ваніль або шоколад.")),
        it("3,50", ["lacteos"],
           M("Cappuccino con nata","Cappuccino with cream","Cappuccino mit Sahne","Cappuccino chantilly","Cappuccino met slagroom","Капучино з вершками"),
           M("Con nata montada.","With whipped cream.","Mit Schlagsahne.","Avec chantilly.","Met slagroom.","Зі збитими вершками.")),
    ])

data = {"sections": sections}
print(json.dumps(data, ensure_ascii=False, indent=2))
